config/routes.rb
Rails.application.routes.draw do
  root to: "brands#index"

  resources :brands do
    resources :models do
      post :sort, on: :collection
    end
    resources :prices, only: [:index, :new, :create]
  end
  
  resources :images, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_one_attached :logo
  has_many :models
  accepts_nested_attributes_for :models
  validates_uniqueness_of :name


  def to_param
    name.parameterize
  end
end

app/models/model.rb
class Model < ApplicationRecord
  belongs_to :brand
  has_ancestry
  has_many_attached :images
  has_many :prices
  accepts_nested_attributes_for :prices, reject_if: proc { |attributes| attributes[:price].blank? }
  has_one :price, -> { order(created_at: :desc) }
end

app/models/price.rb
class Price < ApplicationRecord
  CURRENCIES = ["TRY", "USD", "EUR"]
  belongs_to :model
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  include SortableTreeController::Sort
  before_action :set_brand
  before_action :set_model, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, only: :sort
  sortable_tree 'Model'

  # GET /models
  # GET /models.json
  def index
    @models = @brand.models.arrange(:order => :pos)
  end

  # GET /models/1
  # GET /models/1.json
  def show
  end

  # GET /models/new
  def new
    @model = Model.new
  end

  # GET /models/1/edit
  def edit
  end

  # POST /models
  # POST /models.json
  def create
    @model = @brand.models.new(model_params)

    respond_to do |format|
      if @model.save
        format.html { redirect_to [@brand, @model], notice: 'Model was successfully created.' }
        format.json { render :show, status: :created, location: @model }
      else
        format.html { render :new }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /models/1
  # PATCH/PUT /models/1.json
  def update
    respond_to do |format|
      if @model.update(model_params)
        format.html { redirect_to [@brand, @model], notice: 'Model was successfully updated.' }
        format.json { render :show, status: :ok, location: @model }
      else
        format.html { render :edit }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1
  # DELETE /models/1.json
  def destroy
    @model.destroy
    respond_to do |format|
      format.html { redirect_to models_url, notice: 'Model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_brand
      @brand = Brand.find_by!("lower(name) = ?", params[:brand_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_model
      @model = Model.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def model_params
      params.require(:model).permit(:brand_id, :name, :fuel_type,
        :engine_size, :power, :power_unit, :torque, :transmission,
        :acceleration, :urban_consumption, :extra_urban_consumption,
        :combined_consumption, :top_speed, images: [])
    end
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/views/models/_breadcrumb.html.erb
<%= content_for :breadcrumb do %>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <%= link_to "Anasayfa", root_path %>
      </li>
      <li class="breadcrumb-item active">
        <%= link_to @brand.name, @brand %>
      </li>
      <% @model.ancestors.each do |model| %>
        <li class="breadcrumb-item active">
          <%= link_to model.name, [@brand, model] %>
        </li>
      <% end %>

      <li class="breadcrumb-item active">
        <%= @model.name %>
      </li>
    </ol>
  </nav>
<% end %>

app/views/models/_form.html.erb
<%= form_with(model: [@brand, model], local: true) do |form| %>
  <% if model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(model.errors.count, "error") %> prohibited this model from being saved:</h2>

      <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div class="field images d-flex">
    <% model.images.each do |image| %>
      <div id="<%= dom_id image %>" style="flex: 0 0 60px" class="mr-2">
        <%= image_tag url_for(image.variant(resize: "60x60")), class: "img-thumbnail" %>
        <%= link_to 'sil', image_path(image), remote: true, method: :delete %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :fuel_type %>
    <%= form.text_field :fuel_type %>
  </div>

  <div class="field">
    <%= form.label :engine_size %>
    <%= form.number_field :engine_size %>
  </div>

  <div class="field">
    <%= form.label :power %>
    <%= form.number_field :power %>
  </div>

  <div class="field">
    <%= form.label :power_unit %>
    <%= form.text_field :power_unit %>
  </div>

  <div class="field">
    <%= form.label :torque %>
    <%= form.number_field :torque %>
  </div>

  <div class="field">
    <%= form.label :transmission %>
    <%= form.text_field :transmission %>
  </div>

  <div class="field">
    <%= form.label :acceleration %>
    <%= form.text_field :acceleration %>
  </div>

  <div class="field">
    <%= form.label :urban_consumption %>
    <%= form.text_field :urban_consumption %>
  </div>

  <div class="field">
    <%= form.label :extra_urban_consumption %>
    <%= form.text_field :extra_urban_consumption %>
  </div>

  <div class="field">
    <%= form.label :combined_consumption %>
    <%= form.text_field :combined_consumption %>
  </div>

  <div class="field">
    <%= form.label :top_speed %>
    <%= form.number_field :top_speed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/models/_gallery.html.erb
<div id="gallery" class="carousel slide mt-3" data-ride="carousel">
  <div class="carousel-inner">
    <% @model.images.each_with_index do |image, index| %>
      <div class="carousel-item <%= 'active' if index == 0 %>">
        <%= image_tag url_for(image), class: "d-block w-100" %>
      </div>
    <% end %>
  </div>
  <ol class="carousel-indicators">
    <% @model.images.each_with_index do |image, index| %>
      <li data-target="#gallery" data-slide-to="<%= index %>" class="<%= 'active' if index == 0 %>">
        <%= image_tag image.variant(resize: "60x60") %>
      </li>
    <% end %>
  </ol>
  <a class="carousel-control-prev" href="#gallery" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#gallery" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/models/_info.html.erb
<% if @model.childless? %>
  <dl class="row mt-5">
    <dt class="col-4 text-right">Fuel type:</dt>
    <dd class="col-8"><%= @model.fuel_type %></dd>

    <dt class="col-4 text-right">Engine size:</dt>
    <dd class="col-8"><%= @model.engine_size %></dd>

    <dt class="col-4 text-right">Power:</dt>
    <dd class="col-8"><%= @model.power %></dd>

    <dt class="col-4 text-right">Power unit:</dt>
    <dd class="col-8"><%= @model.power_unit %></dd>

    <dt class="col-4 text-right">Torque:</dt>
    <dd class="col-8"><%= @model.torque %></dd>

    <dt class="col-4 text-right">Transmission:</dt>
    <dd class="col-8"><%= @model.transmission %></dd>

    <dt class="col-4 text-right">Acceleration:</dt>
    <dd class="col-8"><%= @model.acceleration %></dd>

    <dt class="col-4 text-right">Urban consumption:</dt>
    <dd class="col-8"><%= @model.urban_consumption %></dd>

    <dt class="col-4 text-right">Extra urban consumption:</dt>
    <dd class="col-8"><%= @model.extra_urban_consumption %></dd>

    <dt class="col-4 text-right">Combined consumption:</dt>
    <dd class="col-8"><%= @model.combined_consumption %></dd>

    <dt class="col-4 text-right">Top speed:</dt>
    <dd class="col-8"><%= @model.top_speed %></dd>
  </dl>
<% end %>

app/views/models/_model_table.html.erb
<% if !models.empty? %>
  <div class="table-responsive">
    <table class="table mt-5 table-sm">
      <thead class="thead-dark">
        <tr>
          <td>Brand</td>
          <td>Name</td>
          <td>Price</td>
        </tr>
      </thead>

      <tbody>
        <%= render partial: "models/tr_model", collection: models, as: :model %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/models/_top_model_card.html.erb
<div class="col-4 mb-4">
  <div class="card" style="height: 100%">
    <% if model.images.first %>
      <%= link_to [@brand, model] do %>
        <%= image_tag url_for(model.images.first), class: "card-img-top"  %>
      <% end %>
    <% end %>
    <div class="card-body">
      <h5 class="card-title d-flex">
        <%= link_to "#{@brand.name} #{model.name}", [@brand, model] %>

        <%= link_to 'edit', [:edit, @brand, model], class: "ml-auto" %>
      </h5>
    </div>
  </div>
</div>

app/views/models/_tr_model.html.erb
<% model.brand.tap do |brand| %>
  <tr>
    <td>
      <%= link_to brand.name, brand %>
    </td>
    <td>
      <%= link_to model.name, [brand, model] %>
    </td>
    <td>
      TRY
    </td>
  </tr>
<% end %>

app/views/models/edit.html.erb
<h1>Editing Model</h1>

<%= render 'form', model: @model %>

app/views/models/index.html.haml
= render_sortable_tree(@models, { name_method: :name, sort_url: sort_brand_models_url(@brand), max_levels: 3 } )

= link_to "new model", new_brand_model_path(@brand)

app/views/models/new.html.erb
<h1>New Model</h1>

<%= render 'form', model: @model %>

<%= link_to 'Back', brand_models_path(@brand) %>

app/views/models/show.html.erb
<%= render 'breadcrumb' %>

<div class="d-flex">
  <h1><%= @model.name %></h1>
  <%= link_to 'edit', [:edit, @brand, @model], class: "ml-3"  %>

  <% if @model.images.first %>
    <div class="ml-auto" style="flex: 0 0 200px">
      <%= image_tag url_for(@model.images.first), class: "w-100" %>
    </div>
  <% end %>
</div>

<%= render "models/gallery" %>

<%= render "models/model_table", models: @model.children %>

<%= render "models/info" %>